# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermarket',
            old_name='address',
            new_name='adresa',
        ),
        migrations.RenameField(
            model_name='supermarket',
            old_name='name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='supermarket',
            old_name='phone',
            new_name='telefon',
        ),
    ]
