# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20190531_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermarket',
            old_name='adresa',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='supermarket',
            old_name='nume',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supermarket',
            old_name='telefon',
            new_name='phone',
        ),
    ]
